# Generated by Django 3.1.3 on 2021-05-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='inbox_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='inbox_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
